#!/usr/bin/env python3
"""Build strategic AI commerce landscape dataset.

This version organizes examples by stage of delegation:
1) advises/compares
2) acts with permission
3) completes transactions
4) manages purchases over time
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

REQUIRED_COMPANIES = {"Walmart", "Wayfair", "Google", "Visa"}
STAGE_ORDER = [
    "advises_and_compares",
    "acts_with_permission",
    "completes_transactions",
    "manages_purchases_over_time",
]


def case(
    *,
    company: str,
    product_or_agent_name: str,
    stage_of_delegation: str,
    sector: str,
    geography: str,
    market: str,
    recurring_vs_non_recurring: str,
    status: str,
    concise_description: str,
    what_the_ai_does: str,
    consumer_task_delegated: str,
    why_this_stage: str,
    buying_behavior_impact: str,
    source_title: str,
    source_url: str,
    source_type: str,
    date_if_available: str = "",
    notes: str = "",
) -> dict:
    return {
        "company": company,
        "product_or_agent_name": product_or_agent_name,
        "stage_of_delegation": stage_of_delegation,
        "sector": sector,
        "geography": geography,
        "market": market,
        "recurring_vs_non_recurring": recurring_vs_non_recurring,
        "status": status,
        "concise_description": concise_description,
        "what_the_ai_does": what_the_ai_does,
        "consumer_task_delegated": consumer_task_delegated,
        "why_this_stage": why_this_stage,
        "buying_behavior_impact": buying_behavior_impact,
        "source_title": source_title,
        "source_url": source_url,
        "source_type": source_type,
        "date_if_available": date_if_available,
        "notes": notes,
    }


EXAMPLES = [
    # 1) Advises and compares
    case(
        company="Amazon",
        product_or_agent_name="Rufus",
        stage_of_delegation="advises_and_compares",
        sector="Retail",
        geography="North America",
        market="United States",
        recurring_vs_non_recurring="non_recurring",
        status="live",
        concise_description="Embedded shopping assistant that answers questions and compares product options.",
        what_the_ai_does="Interprets shopping intent, summarizes product trade-offs, and guides shortlist creation.",
        consumer_task_delegated="Product research and comparison.",
        why_this_stage="Public evidence is strongest on guidance and comparison, not autonomous checkout.",
        buying_behavior_impact="Reduces time spent manually comparing product pages.",
        source_title="How customers are making more informed shopping decisions with Rufus",
        source_url="https://www.aboutamazon.com/news/retail/how-to-use-amazon-rufus",
        source_type="official",
    ),
    case(
        company="Klarna",
        product_or_agent_name="Klarna AI Shopping Assistant",
        stage_of_delegation="advises_and_compares",
        sector="Retail",
        geography="Europe/North America",
        market="Sweden and global markets",
        recurring_vs_non_recurring="non_recurring",
        status="live",
        concise_description="Conversational shopping assistant for recommendation and merchant comparison.",
        what_the_ai_does="Finds products, compares alternatives, and supports choice refinement.",
        consumer_task_delegated="Shortlisting and value comparison.",
        why_this_stage="Evidence supports recommendation/comparison more than delegated execution.",
        buying_behavior_impact="Shifts from search-tab behavior to guided conversational selection.",
        source_title="Shopping made smarter: Klarna adds more AI features",
        source_url="https://www.klarna.com/international/press/shopping-made-smarter-klarna-adds-more-ai-features-to-its-assistant-powered-by-openai/",
        source_type="official",
        date_if_available="2024-09-19",
    ),
    case(
        company="Instacart",
        product_or_agent_name="Ask Instacart",
        stage_of_delegation="advises_and_compares",
        sector="Grocery",
        geography="North America",
        market="United States",
        recurring_vs_non_recurring="mixed",
        status="live",
        concise_description="AI-guided grocery planning and product guidance tied to basket building.",
        what_the_ai_does="Answers meal and ingredient questions and recommends relevant grocery items.",
        consumer_task_delegated="Discovery and early basket composition.",
        why_this_stage="Primary capability is shopping guidance, with user still driving final purchase decisions.",
        buying_behavior_impact="Cuts planning friction and increases conversion from intent to cart.",
        source_title="Bringing Inspirational, AI-Powered Search to Instacart",
        source_url="https://www.instacart.com/company/updates/bringing-inspirational-ai-powered-search-to-the-instacart-app-with-ask-instacart",
        source_type="official",
        date_if_available="2023-05-31",
    ),
    case(
        company="Wayfair",
        product_or_agent_name="Muse",
        stage_of_delegation="advises_and_compares",
        sector="Retail",
        geography="North America/Europe",
        market="United States and international shoppers",
        recurring_vs_non_recurring="non_recurring",
        status="live",
        concise_description="AI inspiration and recommendation layer for home shopping decisions.",
        what_the_ai_does="Transforms style prompts into product suggestions and visualized options.",
        consumer_task_delegated="Inspiration and option evaluation.",
        why_this_stage="Strong evidence for recommendation and comparison; user still retains transaction control.",
        buying_behavior_impact="Moves shoppers from broad inspiration to a shoppable shortlist faster.",
        source_title="Wayfair Introduces New AI-Powered Tool 'Muse'",
        source_url="https://investor.wayfair.com/news/news-details/2025/Wayfair-Introduces-New-AI-Powered-Tool-Muse-to-Inspire-and-Personalize-the-Home-Shopping-Experience/default.aspx",
        source_type="official",
        date_if_available="2025-02-12",
    ),
    case(
        company="OpenAI",
        product_or_agent_name="Shopping Research in ChatGPT",
        stage_of_delegation="advises_and_compares",
        sector="Shopping assistants",
        geography="Global",
        market="US and international",
        recurring_vs_non_recurring="non_recurring",
        status="announced",
        concise_description="AI shopping research flow for structured product evaluation.",
        what_the_ai_does="Asks clarifying questions and returns tailored option sets and recommendations.",
        consumer_task_delegated="Comparison and pre-purchase analysis.",
        why_this_stage="Publicly evidenced capability centers on recommendation, not autonomous buying.",
        buying_behavior_impact="Consolidates fragmented research tasks into one conversational workflow.",
        source_title="Introducing shopping research in ChatGPT",
        source_url="https://openai.com/index/chatgpt-shopping-research/",
        source_type="official",
        date_if_available="2025-11-24",
    ),
    case(
        company="Rakuten",
        product_or_agent_name="Rakuten AI Assistant",
        stage_of_delegation="advises_and_compares",
        sector="Marketplace",
        geography="Asia",
        market="Japan",
        recurring_vs_non_recurring="non_recurring",
        status="live",
        concise_description="Marketplace AI concierge for intent-led product discovery and recommendation.",
        what_the_ai_does="Uses conversational inputs to propose personalized product options in Rakuten Ichiba.",
        consumer_task_delegated="Marketplace search and comparison.",
        why_this_stage="Evidence supports strong recommendation behavior; checkout delegation remains limited.",
        buying_behavior_impact="Encourages AI-led shopping discovery over manual category navigation.",
        source_title="Rakuten launches agentic AI tools in Rakuten Ichiba",
        source_url="https://corp.rakuten.co.jp/news/press/2026/0105_02.html",
        source_type="official",
        date_if_available="2026-01-05",
    ),
    case(
        company="Naver",
        product_or_agent_name="Shopping AI Agent",
        stage_of_delegation="advises_and_compares",
        sector="Marketplace",
        geography="Asia",
        market="South Korea",
        recurring_vs_non_recurring="non_recurring",
        status="pilot",
        concise_description="Conversational shopping agent for personalized recommendations.",
        what_the_ai_does="Uses user intent and preference context to recommend and compare products.",
        consumer_task_delegated="Product discovery and evaluation.",
        why_this_stage="Current public evidence emphasizes recommendation beta behavior rather than transaction execution.",
        buying_behavior_impact="Replaces keyword search loops with iterative AI-guided comparison.",
        source_title="Naver launches shopping AI agent beta",
        source_url="https://www.aitimes.com/news/articleView.html?idxno=207310",
        source_type="news",
        date_if_available="2026-02-26",
    ),
    # 2) Acts with permission
    case(
        company="Walmart",
        product_or_agent_name="Sparky",
        stage_of_delegation="acts_with_permission",
        sector="Retail",
        geography="North America",
        market="United States",
        recurring_vs_non_recurring="non_recurring",
        status="live",
        concise_description="Retail assistant that advances from recommendations toward action support in shopping flows.",
        what_the_ai_does="Guides choices and helps users proceed through practical next-step actions.",
        consumer_task_delegated="Decision support plus action initiation with user control.",
        why_this_stage="Public positioning is agentic and action-oriented, but not broad fully autonomous purchase management.",
        buying_behavior_impact="Increases willingness to let AI move from advice into assisted action.",
        source_title="Walmart: The Future of Shopping Is Agentic. Meet Sparky.",
        source_url="https://corporate.walmart.com/news/2025/06/06/walmart-the-future-of-shopping-is-agentic-meet-sparky",
        source_type="official",
        date_if_available="2025-06-06",
    ),
    case(
        company="Google",
        product_or_agent_name="AI Mode Shopping + Agentic Checkout",
        stage_of_delegation="acts_with_permission",
        sector="Retail",
        geography="North America",
        market="United States",
        recurring_vs_non_recurring="non_recurring",
        status="announced",
        concise_description="AI shopping flow that can advance user-selected items toward purchase actions.",
        what_the_ai_does="Tracks prices, compares options, and proceeds with user-approved next steps.",
        consumer_task_delegated="Execution of purchase steps with explicit user permission.",
        why_this_stage="Public evidence highlights approval-based agentic actions rather than fully autonomous commerce management.",
        buying_behavior_impact="Reduces friction between decision and action in buying journeys.",
        source_title="Google Shopping launches agentic checkout and more AI shopping tools",
        source_url="https://www.blog.google/products/shopping/agentic-checkout-holiday-ai-shopping/",
        source_type="official",
        date_if_available="2025-05-20",
    ),
    case(
        company="Perplexity",
        product_or_agent_name="Buy with Pro",
        stage_of_delegation="acts_with_permission",
        sector="Shopping assistants",
        geography="North America",
        market="United States",
        recurring_vs_non_recurring="non_recurring",
        status="live",
        concise_description="AI search assistant that supports transition from recommendation into buying steps.",
        what_the_ai_does="Finds options and enables user-driven purchase progression in flow.",
        consumer_task_delegated="Action execution once the user validates product selection.",
        why_this_stage="Evidence indicates action support with user involvement, not persistent autonomous management.",
        buying_behavior_impact="Collapses search, shortlist, and action initiation into one interface.",
        source_title="AI startup Perplexity adds shopping features as search competition tightens",
        source_url="https://www.reuters.com/technology/artificial-intelligence/ai-startup-perplexity-adds-shopping-features-search-competition-tightens-2024-11-18/",
        source_type="news",
        date_if_available="2024-11-18",
    ),
    case(
        company="Visa",
        product_or_agent_name="Trusted Agent Protocol / Intelligent Commerce",
        stage_of_delegation="acts_with_permission",
        sector="Payments",
        geography="Global",
        market="Global",
        recurring_vs_non_recurring="mixed",
        status="announced",
        concise_description="Payment network protocol for trusted agent actions under user consent controls.",
        what_the_ai_does="Enables AI agents to initiate payment actions within guardrails and authentication requirements.",
        consumer_task_delegated="Payment-step execution with explicit approval boundaries.",
        why_this_stage="Core value is secure permissioned action, not independent purchase completion at scale.",
        buying_behavior_impact="Builds trust in allowing AI to act on payment-related tasks.",
        source_title="Visa Unveils Trusted Agent Protocol for AI Commerce",
        source_url="https://corporate.visa.com/en/sites/visa-perspectives/newsroom/visa-unveils-trusted-agent-protocol-for-ai-commerce.html",
        source_type="official",
        date_if_available="2025-10-29",
    ),
    case(
        company="Papernest",
        product_or_agent_name="Contract Management and Switching Assistant",
        stage_of_delegation="acts_with_permission",
        sector="Household expense optimization",
        geography="Europe",
        market="France",
        recurring_vs_non_recurring="recurring",
        status="live",
        concise_description="Assistant that helps users handle switching and provider admin tasks for recurring bills.",
        what_the_ai_does="Supports comparison, switching and contract setup steps across energy, internet and insurance.",
        consumer_task_delegated="Switching and recurring-service administrative actions.",
        why_this_stage="Evidence supports guided execution with user intent, rather than autonomous recurring management.",
        buying_behavior_impact="Reduces switching friction and increases recurring expense optimization behavior.",
        source_title="papernest, LA solution pour gérer tous vos contrats",
        source_url="https://www.papernest.com/",
        source_type="official",
    ),
    case(
        company="Goji Mobile",
        product_or_agent_name="ChatBarry",
        stage_of_delegation="acts_with_permission",
        sector="Telecom",
        geography="Europe/North America",
        market="United Kingdom and US relevance",
        recurring_vs_non_recurring="recurring",
        status="live",
        concise_description="AI plan advisor supporting consumers who want to switch to better mobile tariffs.",
        what_the_ai_does="Collects usage needs, recommends plans, and supports switch-ready decision paths.",
        consumer_task_delegated="Tariff fit assessment and switch preparation.",
        why_this_stage="Supports action readiness but final switch execution remains user-controlled.",
        buying_behavior_impact="Encourages proactive plan optimization rather than passive renewal behavior.",
        source_title="Meet ChatBarry: The AI Matchmaker for Phone Plans",
        source_url="https://www.gojimobile.com/blog/meet-chatbarry",
        source_type="official",
        date_if_available="2024-09-28",
    ),
    # 3) Completes transactions
    case(
        company="Mastercard",
        product_or_agent_name="Agent Pay",
        stage_of_delegation="completes_transactions",
        sector="Payments",
        geography="Global",
        market="Multi-region",
        recurring_vs_non_recurring="mixed",
        status="live",
        concise_description="Payments infrastructure for AI agents to complete authenticated purchases.",
        what_the_ai_does="Executes payment transactions with consumer authorization and embedded controls.",
        consumer_task_delegated="Final payment completion.",
        why_this_stage="Public evidence includes live transaction execution by agentic payment flows.",
        buying_behavior_impact="Normalizes AI-mediated checkout completion in trusted rails.",
        source_title="Mastercard advances agentic payments with live transactions",
        source_url="https://www.mastercard.com/news/latin-america/en/newsroom/press-releases/pr-en/2026/march/mastercard-advances-agentic-payments-in-latin-america-and-the-caribbean-with-live-transactions-completed-across-the-region/",
        source_type="official",
        date_if_available="2026-03-30",
    ),
    case(
        company="Fliggy",
        product_or_agent_name="AskMe AI Travel Assistant",
        stage_of_delegation="completes_transactions",
        sector="Travel",
        geography="Asia",
        market="China",
        recurring_vs_non_recurring="non_recurring",
        status="live",
        concise_description="AI travel assistant that converts user intent into bookable options and bookings.",
        what_the_ai_does="Builds itinerary options and supports direct booking progression.",
        consumer_task_delegated="Trip booking execution.",
        why_this_stage="Public evidence supports transaction completion in travel booking workflows.",
        buying_behavior_impact="Accelerates conversion from planning to reservation in a single AI flow.",
        source_title="Fliggy launches AI travel assistant AskMe",
        source_url="https://www.prnewswire.com/apac/news-releases/fliggy-launches-ai-travel-assistant-askme-to-make-customized-travel-even-more-accessible-302431294.html",
        source_type="press_release",
        date_if_available="2025-04-16",
    ),
    case(
        company="Trip.com",
        product_or_agent_name="TripGenie",
        stage_of_delegation="completes_transactions",
        sector="Travel",
        geography="Asia",
        market="Singapore and global customer base",
        recurring_vs_non_recurring="non_recurring",
        status="live",
        concise_description="AI travel assistant linking recommendations to bookable inventory.",
        what_the_ai_does="Supports plan creation and booking progression in conversational flow.",
        consumer_task_delegated="Reservation and booking steps.",
        why_this_stage="Public evidence indicates direct links to transactable offers and booking completion pathways.",
        buying_behavior_impact="Shrinks planning-to-booking time for travel purchases.",
        source_title="Introducing TripGenie: AI travel assistant by Trip.com",
        source_url="https://www.trip.com/newsroom/introducing-tripgenie-groundbreaking-ai-travel-assistant/",
        source_type="official",
        date_if_available="2024-07-25",
    ),
    case(
        company="Google x Wayfair",
        product_or_agent_name="UCP / AI Mode checkout pathways",
        stage_of_delegation="completes_transactions",
        sector="Retail infrastructure",
        geography="North America",
        market="United States",
        recurring_vs_non_recurring="non_recurring",
        status="announced",
        concise_description="Merchant integration that enables AI-assisted checkout progression.",
        what_the_ai_does="Connects product discovery in AI interfaces to checkout-enabled merchant flows.",
        consumer_task_delegated="Checkout handoff and purchase completion steps.",
        why_this_stage="Evidence supports transaction-oriented integration patterns, beyond pure advice.",
        buying_behavior_impact="Reduces channel-switching between discovery and checkout.",
        source_title="Wayfair partners with Google to make it easier to shop for your home",
        source_url="https://www.aboutwayfair.com/category/tech-innovation/wayfair-partners-with-google-to-make-it-easier-to-shop-for-your-home",
        source_type="official",
        date_if_available="2026-01-12",
    ),
    case(
        company="Shopee / Sea with Google",
        product_or_agent_name="Agentic shopping prototype",
        stage_of_delegation="completes_transactions",
        sector="Marketplace",
        geography="Asia",
        market="Southeast Asia",
        recurring_vs_non_recurring="non_recurring",
        status="announced",
        concise_description="Emerging agentic shopping prototype for end-to-end e-commerce tasks.",
        what_the_ai_does="Targets multi-step purchase flows from search and comparison toward transaction completion.",
        consumer_task_delegated="Purchase flow execution in marketplace context.",
        why_this_stage="Publicly framed around agentic shopping execution patterns, though still early-stage.",
        buying_behavior_impact="Signals delegated purchase completion entering SEA mobile commerce ecosystems.",
        source_title="Google, Shopee-owner Sea to develop AI tools for e-commerce, gaming",
        source_url="https://www.reuters.com/world/asia-pacific/google-shopee-owner-sea-develop-ai-tools-e-commerce-gaming-2026-02-19/",
        source_type="news",
        date_if_available="2026-02-19",
    ),
    # 4) Manages purchases over time
    case(
        company="MoneySuperMarket",
        product_or_agent_name="ChatGPT Comparison App",
        stage_of_delegation="manages_purchases_over_time",
        sector="Comparison engine",
        geography="Europe",
        market="United Kingdom",
        recurring_vs_non_recurring="recurring",
        status="live",
        concise_description="Conversational comparison journey for recurring household and financial expenses.",
        what_the_ai_does="Keeps users in an ongoing optimization loop for recurring bills and financial products.",
        consumer_task_delegated="Repeat comparison and renewal-time optimization.",
        why_this_stage="Its recurring-bill relevance is strongest as a continuous management behavior over time.",
        buying_behavior_impact="Makes recurring expense optimization more frequent and proactive.",
        source_title="MoneySuperMarket brings AI-powered comparison to ChatGPT",
        source_url="https://www.insurancebusinessmag.com/uk/news/technology/moneysupermarket-brings-aipowered-comparison-to-chatgpt-566181.aspx",
        source_type="news",
        date_if_available="2026-03-27",
    ),
    case(
        company="Rocket Money",
        product_or_agent_name="Bill Negotiation",
        stage_of_delegation="manages_purchases_over_time",
        sector="Consumer fintech",
        geography="North America",
        market="United States",
        recurring_vs_non_recurring="recurring",
        status="live",
        concise_description="Negotiation service focused on reducing recurring household bills.",
        what_the_ai_does="Coordinates bill-lowering workflows and ongoing savings opportunities.",
        consumer_task_delegated="Recurring bill negotiation and spend optimization.",
        why_this_stage="Core value is continuous post-purchase cost management rather than one-time transaction support.",
        buying_behavior_impact="Turns passive bill payment into active recurring optimization behavior.",
        source_title="Get better rates on your bills",
        source_url="https://www.rocketmoney.com/feature/lower-your-bills",
        source_type="official",
    ),
    case(
        company="Billshark",
        product_or_agent_name="Bill Negotiation Service",
        stage_of_delegation="manages_purchases_over_time",
        sector="Consumer services",
        geography="North America",
        market="United States",
        recurring_vs_non_recurring="recurring",
        status="live",
        concise_description="Delegated recurring-expense negotiation for telecom and household bills.",
        what_the_ai_does="Runs negotiation processes to lower monthly provider costs over time.",
        consumer_task_delegated="Ongoing bill reduction management.",
        why_this_stage="Demonstrates managed post-purchase optimization, beyond discovery/comparison tasks.",
        buying_behavior_impact="Institutionalizes outsourced savings behavior across recurring categories.",
        source_title="Billshark",
        source_url="https://www.billshark.com/",
        source_type="official",
    ),
    case(
        company="Pine",
        product_or_agent_name="Lower Your Bills",
        stage_of_delegation="manages_purchases_over_time",
        sector="Consumer services",
        geography="North America",
        market="United States",
        recurring_vs_non_recurring="recurring",
        status="live",
        concise_description="Automated recurring-expense optimization and negotiation support.",
        what_the_ai_does="Handles bill-reduction processes for internet, phone, and related recurring services.",
        consumer_task_delegated="Recurring bill management and savings execution.",
        why_this_stage="Positioned as ongoing management of monthly spend, not one-time advice.",
        buying_behavior_impact="Increases long-term use of delegated savings services.",
        source_title="Lower your bills",
        source_url="https://www.19pine.ai/feature/lower-your-bills",
        source_type="official",
    ),
    case(
        company="Selectra",
        product_or_agent_name="Multi-service tariff comparison",
        stage_of_delegation="manages_purchases_over_time",
        sector="Comparison engine",
        geography="Europe",
        market="France and pan-European markets",
        recurring_vs_non_recurring="recurring",
        status="live",
        concise_description="Comparison-led service helping households repeatedly optimize utilities and telecom contracts.",
        what_the_ai_does="Supports recurring tariff checks and switching decisions across categories.",
        consumer_task_delegated="Recurring contract optimization and periodic switching decisions.",
        why_this_stage="Operational pattern is repeat optimization over time, aligned with managed spending behavior.",
        buying_behavior_impact="Normalizes recurring household cost reviews as a continuous behavior.",
        source_title="Selectra group | Corporate website page",
        source_url="https://www.selectra.com/",
        source_type="official",
    ),
    case(
        company="Paytm",
        product_or_agent_name="AI-first payments app",
        stage_of_delegation="manages_purchases_over_time",
        sector="Payments",
        geography="Asia",
        market="India",
        recurring_vs_non_recurring="recurring",
        status="live",
        concise_description="Wallet/app features that help users monitor and manage recurring personal spend.",
        what_the_ai_does="Provides AI categorization and spend intelligence across recurring payment behavior.",
        consumer_task_delegated="Monitoring and optimization of ongoing expenses.",
        why_this_stage="Public evidence is strongest on continuous spend management rather than autonomous purchases.",
        buying_behavior_impact="Encourages routine budget optimization within daily payment workflows.",
        source_title="Paytm launches all-new app with AI-first features",
        source_url="https://paytm.com/blog/artificial-intelligence/paytm-launches-the-all-new-app-combining-clean-interface-and-ai-first-features-to-redefine-everyday-payments/",
        source_type="official",
    ),
    case(
        company="Deutsche Telekom",
        product_or_agent_name="Magenta AI",
        stage_of_delegation="manages_purchases_over_time",
        sector="Telecom",
        geography="Europe",
        market="Germany",
        recurring_vs_non_recurring="recurring",
        status="live",
        concise_description="AI assistant embedded in telecom customer ecosystem for service guidance and recurring interactions.",
        what_the_ai_does="Supports ongoing customer interactions in app/device environments tied to telecom services.",
        consumer_task_delegated="Recurring telecom service management support.",
        why_this_stage="Most evident role is in ongoing account/service interactions over time.",
        buying_behavior_impact="Increases continuous AI touchpoints in recurring telecom journeys.",
        source_title="“Our” AI-phone brings „AI for everyone“ | Deutsche Telekom",
        source_url="https://www.telekom.com/en/media/media-information/archive/our-ai-phone-brings-ai-for-everyone-1095198",
        source_type="official",
    ),
    case(
        company="Alibaba (Taobao/Tmall)",
        product_or_agent_name="Taobao Wenwen",
        stage_of_delegation="advises_and_compares",
        sector="Retail",
        geography="Asia",
        market="China",
        recurring_vs_non_recurring="non_recurring",
        status="live",
        concise_description="Large-scale marketplace AI for recommendation and product trade-off guidance.",
        what_the_ai_does="Supports conversational comparison, recommendation, and decision support.",
        consumer_task_delegated="Shopping research and option evaluation.",
        why_this_stage="Strong evidence for advisory/comparison at scale; less explicit autonomous transaction control.",
        buying_behavior_impact="Speeds high-frequency retail decision-making in mobile commerce flows.",
        source_title="Taobao and Tmall Upgrades Consumer Shopping Experience and Merchant Support Through AI",
        source_url="https://www.alibabagroup.com/en-US/document-1738398759789789184",
        source_type="official",
        date_if_available="2024-06-18",
    ),
    case(
        company="Alibaba Qwen App",
        product_or_agent_name="Agentic Service Execution",
        stage_of_delegation="acts_with_permission",
        sector="Super-app ecosystem",
        geography="Asia",
        market="China",
        recurring_vs_non_recurring="mixed",
        status="live",
        concise_description="Cross-service assistant for shopping, travel, and payment actions inside one conversational surface.",
        what_the_ai_does="Coordinates multi-step consumer tasks across ecosystem services with user intent.",
        consumer_task_delegated="Action execution across commerce and service tasks.",
        why_this_stage="Evidence supports broad permissioned actions; conservative classification avoids over-claiming full autonomy.",
        buying_behavior_impact="Reduces app switching and increases AI-led task completion.",
        source_title="Alibaba’s Qwen App Advances Agentic AI Strategy",
        source_url="https://www.alibabacloud.com/blog/alibaba%25E2%2580%2599s-qwen-app-advances-agentic-ai-strategy-by-turning-core-ecosystem-services-into-executable-ai-capabilities_602801",
        source_type="official",
        date_if_available="2026-01-15",
    ),
    case(
        company="JD.com",
        product_or_agent_name="ChatJD / AI Commerce Services",
        stage_of_delegation="advises_and_compares",
        sector="Retail",
        geography="Asia",
        market="China",
        recurring_vs_non_recurring="mixed",
        status="live",
        concise_description="Marketplace AI capabilities for recommendation and consumer shopping support.",
        what_the_ai_does="Improves matching and recommendation quality in e-commerce interactions.",
        consumer_task_delegated="Search refinement and choice support.",
        why_this_stage="Public evidence is strongest on recommendation and interaction support.",
        buying_behavior_impact="Decreases manual exploration effort in large-catalog environments.",
        source_title="JD.com Announces Enhanced Spring Dawn Initiative with New AI Service Package",
        source_url="https://jdcorporateblog.com/jd-com-announces-enhanced-spring-dawn-initiative-with-new-ai-service-package/",
        source_type="official",
        date_if_available="2024-03-18",
    ),
    case(
        company="Kakao",
        product_or_agent_name="Kanana / Shopping How AI flows",
        stage_of_delegation="advises_and_compares",
        sector="Marketplace",
        geography="Asia",
        market="South Korea",
        recurring_vs_non_recurring="non_recurring",
        status="live",
        concise_description="AI-enhanced shopping discovery in chat and commerce surfaces.",
        what_the_ai_does="Supports recommendation and shopping exploration with contextual signals.",
        consumer_task_delegated="Discovery and decision support.",
        why_this_stage="Evidence supports advisory/recommendation behavior more than direct autonomous purchase execution.",
        buying_behavior_impact="Blends messaging and shopping, reducing discovery friction.",
        source_title="Start shopping smart with Shopping How | Kakao",
        source_url="https://www.kakaocorp.com/page/service/service/ShoppingHow?lang=en",
        source_type="official",
    ),
]

REJECTED = [
    {
        "company": "Pinduoduo",
        "reason": "insufficient proof of agentic or commerce relevance",
        "detail": "Public evidence reviewed was mainly hiring activity, not a clearly validated consumer AI agent workflow.",
    },
    {"company": "Generic Instagram live auction claims", "reason": "too speculative", "detail": "No strong public proof of AI-agent-led transaction execution."},
    {
        "company": "General telco support chatbots",
        "reason": "generic chatbot only",
        "detail": "Excluded where no clear comparison, switching, optimization, or transaction impact was documented.",
    },
]


def summarize(examples: list[dict]) -> dict:
    status_counts = {"live": 0, "pilot": 0, "announced": 0, "demo": 0}
    for e in examples:
        if e["status"] in status_counts:
            status_counts[e["status"]] += 1
    required_present = sorted({e["company"] for e in examples}.intersection(REQUIRED_COMPANIES))
    return {
        "total_examples": len(examples),
        "stages": {
            s: sum(1 for e in examples if e["stage_of_delegation"] == s) for s in STAGE_ORDER
        },
        "sectors_covered": sorted({e["sector"] for e in examples}),
        "geographies_covered": sorted({e["geography"] for e in examples}),
        "status_breakdown": status_counts,
        "required_companies_present": required_present,
        "required_companies_missing": sorted(list(REQUIRED_COMPANIES - set(required_present))),
    }


def main() -> None:
    out_dir = Path("data")
    out_dir.mkdir(parents=True, exist_ok=True)

    # Deduplicate (company + product).
    deduped: list[dict] = []
    seen = set()
    for e in EXAMPLES:
        key = (e["company"].lower().strip(), e["product_or_agent_name"].lower().strip())
        if key in seen:
            continue
        seen.add(key)
        deduped.append(e)

    # Sort by stage then market/company.
    order_idx = {s: i for i, s in enumerate(STAGE_ORDER)}
    deduped.sort(key=lambda x: (order_idx.get(x["stage_of_delegation"], 99), x["market"], x["company"]))

    payload = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "methodology": {
            "public_sources_only": True,
            "curated_not_raw_scrape": True,
            "deduplicated": True,
            "selection_target": "16-28 distinct examples",
        },
        "framing": {
            "top_message": (
                "AI Commerce is evolving from recommendation tools to execution-capable agents. "
                "The strategic question is delegation maturity: where AI only advises, where it acts with permission, "
                "where it completes transactions, and where it manages spending continuously over time."
            )
        },
        "summary": summarize(deduped),
        "stage_intros": {
            "advises_and_compares": (
                "This stage matters because it shifts the discovery and evaluation burden from consumers to AI. "
                "Adoption here expands quickly because trust requirements are lower while productivity gains are immediate."
            ),
            "acts_with_permission": (
                "This stage marks the transition from insight to execution. "
                "Consumer trust is built through approval checkpoints while AI begins handling practical commerce actions."
            ),
            "completes_transactions": (
                "At this stage, AI directly drives conversion by completing key transaction steps. "
                "The strategic unlock is lower friction and faster intent-to-purchase movement."
            ),
            "manages_purchases_over_time": (
                "This stage is structurally the most disruptive because AI manages recurring spend and post-purchase optimization. "
                "Value creation shifts from one-time conversion toward lifetime consumer outcome management."
            ),
        },
        "examples": deduped,
    }

    (out_dir / "ai_commerce_examples.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=True),
        encoding="utf-8",
    )
    (out_dir / "ai_commerce_rejections.json").write_text(
        json.dumps(
            {
                "generated_at_utc": datetime.now(timezone.utc).isoformat(),
                "rejected_count": len(REJECTED),
                "rejections": REJECTED,
            },
            indent=2,
            ensure_ascii=True,
        ),
        encoding="utf-8",
    )
    print("Wrote data/ai_commerce_examples.json")
    print("Wrote data/ai_commerce_rejections.json")
    print(f"Accepted examples: {len(deduped)}")


if __name__ == "__main__":
    main()
